#tail -f flask.log 
```shell 
[vagrant@OpsDev2 vagrant]$ tail -f flask.log 
2016-06-01 19:50:17,105 - app - views.py- DEBUG - 访问首页
2016-06-01 19:54:35,909 - app - views.py- DEBUG - 访问首页


^C
[vagrant@OpsDev2 vagrant]$ tail -f flask.log 
2016-06-01 19:50:17,105 - app - views.py- DEBUG - 访问首页
2016-06-01 19:54:35,909 - app - views.py- DEBUG - 访问首页
2016-06-01 20:19:58,910 - app - views.py- DEBUG - 访问首页
2016-06-01 20:32:12,401 - app - views.py- DEBUG - 用户请求的content-type为： , 不予处理

2016-06-01 21:03:58,718 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:07:55,683 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:11:23,415 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:12:48,596 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:17:13,684 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:17:33,771 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:17:44,843 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:18:01,753 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:19:51,960 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:21:05,223 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:21:29,237 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:22:14,404 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:23:45,954 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:23:57,608 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:26:30,473 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:28:05,912 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:28:05,919 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
2016-06-01 21:28:42,910 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:28:42,916 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
2016-06-01 21:29:53,899 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:29:53,908 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
2016-06-01 21:37:56,801 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:37:56,810 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
2016-06-01 21:46:59,502 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:46:59,509 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
2016-06-01 21:47:34,490 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
2016-06-01 21:47:34,498 - app - views.py- DEBUG - 请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
```
#web server log

```shell

Last login: Wed Jun  1 19:50:35 2016 from 10.0.2.2
Welcome to your Vagrant-built virtual machine.
[vagrant@OpsDev2 ~]$ cd /vagrant
[vagrant@OpsDev2 vagrant]$ ls
app         flask.log                    modules                   test
base        jsonrpc.py                   mycmdb.sublime-project    Vagrantfile
config.py   jsonrpc.pyc                  mycmdb.sublime-workspace
config.pyc  lessson02.sublime-workspace  readme.md
document    manage.py                    requirements.txt
[vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    from app import create_app, db
  File "/vagrant/app/__init__.py", line 3, in <module>
    from flask import Flask
ImportError: No module named flask
[vagrant@OpsDev2 vagrant]$ source /data/python27env/bin/activate
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:14]:
访问首页
--------------------------------------------------------------------------------
10.0.2.2 - - [01/Jun/2016 20:19:58] "GET / HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:31]:
用户请求的content-type为： , 不予处理
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 20:32:12] "POST /api HTTP/1.1" 400 -
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
127.0.0.1 - - [01/Jun/2016 20:39:15] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 25, in api
    current_app.logger.debug("请求json数据为： {}".format(json.dumps(jsonData)))
NameError: global name 'json' is not defined
127.0.0.1 - - [01/Jun/2016 20:42:59] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 25, in api
    current_app.logger.debug("请求json数据为： {}".format(json.dumps(jsonData)))
NameError: global name 'json' is not defined
127.0.0.1 - - [01/Jun/2016 20:49:31] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 25, in api
    current_app.logger.debug("请求json数据为： {}".format(json.dumps(jsonData)))
NameError: global name 'json' is not defined
127.0.0.1 - - [01/Jun/2016 20:56:22] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 25, in api
    current_app.logger.debug("请求json数据为： {}".format(json.dumps(jsonData)))
NameError: global name 'json' is not defined
127.0.0.1 - - [01/Jun/2016 21:00:21] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 25, in api
    current_app.logger.debug("请求json数据为： {}".format(json.dumps(jsonData)))
NameError: global name 'json' is not defined
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 9
    from __future__ import unicode_literals
SyntaxError: from __future__ imports must occur at the beginning of the file
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 9
    from __future__ import unicode_literals
SyntaxError: from __future__ imports must occur at the beginning of the file
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:26]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:03:58] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 27, in api
    jsonrpc = JsonRpc()
NameError: global name 'JsonRpc' is not defined
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 12, in <module>
    from app.base import JsonRpc
ImportError: No module named base
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 12, in <module>
    from app.base import JsonRpc
ImportError: No module named base
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 12, in <module>
    from app.base import JsonRpc
ImportError: cannot import name JsonRpc
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:07:55] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc()
TypeError: __init__() takes exactly 2 arguments (1 given)
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:11:23] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc(jsonData)
  File "/vagrant/app/base/__init__.py", line 30, in __init__
    print "模块名：%s，函数名：%s" % (self.module_name, self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2: ordinal not in range(128)
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:12:48] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc(json.dumps(jsonData))
  File "/vagrant/app/base/__init__.py", line 28, in __init__
    self.module_name, self.funcname = self.jsondata.get(
AttributeError: 'str' object has no attribute 'get'
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:17:13] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
NameError: global name 'jsonrpc' is not defined
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:17:33] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 31, in api
    return json.dumps(ret, ensure_ascii=False)
NameError: global name 'ret' is not defined
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:17:44] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1478, in full_dispatch_request
    response = self.make_response(rv)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1566, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:18:01] "POST /api HTTP/1.1" 400 -
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:19:51] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc("{}".format(json.dumps(jsonData)))
  File "/vagrant/app/base/__init__.py", line 28, in __init__
    self.module_name, self.funcname = self.jsondata.get(
AttributeError: 'unicode' object has no attribute 'get'
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:21:05] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc("{}".format(jsonData))
  File "/vagrant/app/base/__init__.py", line 28, in __init__
    self.module_name, self.funcname = self.jsondata.get(
AttributeError: 'unicode' object has no attribute 'get'
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:21:29] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc(jsonData)
  File "/vagrant/app/base/__init__.py", line 30, in __init__
    print "模块名：%s，函数名：%s" % (self.module_name, self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 2: ordinal not in range(128)
 * Detected change in '/vagrant/app/base/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:22:14] "POST /api HTTP/1.1" 200 -
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
127.0.0.1 - - [01/Jun/2016 21:23:45] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 28, in api
    jsonrpc = JsonRpc(json.dumps(jsonData))
  File "/vagrant/app/base/__init__.py", line 28, in __init__
    self.module_name, self.funcname = self.jsondata.get(
AttributeError: 'str' object has no attribute 'get'
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:23:57] "POST /api HTTP/1.1" 200 -
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
 * Detected change in '/vagrant/app/main/views.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:26:30] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:28:05] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
127.0.0.1 - - [01/Jun/2016 21:28:05] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 144, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 132, in validata_hasFunction
    "模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:28:42] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
127.0.0.1 - - [01/Jun/2016 21:28:42] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 144, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 132, in validata_hasFunction
    "模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
 * Detected change in '/vagrant/app/base/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:29:53] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
127.0.0.1 - - [01/Jun/2016 21:29:53] "POST /api HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 143, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 131, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)
 * Detected change in '/vagrant/app/base/__init__.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 12, in <module>
    from app.base import JsonRpc
  File "/vagrant/app/base/__init__.py", line 12, in <module>
    sys.setdefaultencoding('utf-8')
AttributeError: 'module' object has no attribute 'setdefaultencoding'
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'development')
  File "/vagrant/app/__init__.py", line 14, in create_app
    from .main import main as main_blugprint
  File "/vagrant/app/main/__init__.py", line 6, in <module>
    from . import views, errors
  File "/vagrant/app/main/views.py", line 12, in <module>
    from app.base import JsonRpc
  File "/vagrant/app/base/__init__.py", line 13, in <module>
    sys.setdefaultencoding('utf-8')
AttributeError: 'module' object has no attribute 'setdefaultencoding'
(python27env) [vagrant@OpsDev2 vagrant]$ python manage.py runserver -h 0.0.0.0 -p 8000
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:37:56] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
2016-06-01 21:37:56 模块idc没有此函数getIdc_err
2016-06-01 21:37:56 ID不正确，应该为1
2016-06-01 21:37:56 jsonrpc版本不正确，应该为2.0
2016-06-01 21:37:56 你需要登录后才能访问此方法！
127.0.0.1 - - [01/Jun/2016 21:37:56] "POST /api HTTP/1.1" 200 -
 * Detected change in '/vagrant/app/base/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:46:59] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
--------------------------------------------------------------------------------
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
2016-06-01 21:46:59 模块idc没有此函数getIdc_err
2016-06-01 21:46:59 ID不正确，应该为1
2016-06-01 21:46:59 jsonrpc版本不正确，应该为2.0
2016-06-01 21:46:59 你需要登录后才能访问此方法！
127.0.0.1 - - [01/Jun/2016 21:46:59] "POST /api HTTP/1.1" 200 -
 * Detected change in '/vagrant/app/base/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "2.0", "params": {"idcId": "2"}, "method": "idc.getIdc", "auth": "kch", "id": "1"}
--------------------------------------------------------------------------------
模块名：idc，函数名：getIdc
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
id:1
jsonRpcVersion:2.0
whitelist:idc.getIdc
验证通过：等待调用方法！
测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}
127.0.0.1 - - [01/Jun/2016 21:47:34] "POST /api HTTP/1.1" 200 -
--------------------------------------------------------------------------------
DEBUG in views [/vagrant/app/main/views.py:27]:
请求json数据为： {"jsonRpcVersion": "1.0", "params": {"idcId": "2"}, "method": "idc.getIdc_err", "auth": "kch", "id": "2"}
--------------------------------------------------------------------------------
模块名：idc，函数名：getIdc_err
<module 'modules.idc' from '/vagrant/modules/idc.pyc'>
2016-06-01 21:47:34 模块idc没有此函数getIdc_err
2016-06-01 21:47:34 ID不正确，应该为1
2016-06-01 21:47:34 jsonrpc版本不正确，应该为2.0
2016-06-01 21:47:34 你需要登录后才能访问此方法！
127.0.0.1 - - [01/Jun/2016 21:47:34] "POST /api HTTP/1.1" 200 -
 * Detected change in '/vagrant/app/base/__init__.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 292-620-038

```

#testaip.py exec log

```shell
_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 144, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 132, in validata_hasFunction
    "模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 144, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 132, in validata_hasFunction
    "模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

-->

(python27env) [vagrant@OpsDev2 test]$ python testAPI.py 
200
"{\n    \"jsonrpc\": \"2.0\", \n    \"result\": \"测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}\", \n    \"id\": 1\n}"
500
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128) // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
        type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does
         not by accident trigger a request to /favicon.ico which might
         change the application state. -->
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 140466947021712,
          CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "rvjXZMn6gDLfzKS42zS4";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>UnicodeDecodeError</h1>
<div class="detail">
  <p class="errormsg">UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-140466947021584">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <div class="source"><pre class="line before"><span class="ws">                                </span>'Flask.blueprints instead'), stacklevel=2)</pre>
<pre class="line before"><span class="ws">        </span>return self.blueprints</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;Shortcut for :attr:`wsgi_app`.&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def __repr__(self):</pre>
<pre class="line after"><span class="ws">        </span>return '&lt;%s %r&gt;' % (</pre>
<pre class="line after"><span class="ws">            </span>self.__class__.__name__,</pre>
<pre class="line after"><span class="ws">            </span>self.name,</pre></div>
</div>

<li><div class="frame" id="frame-140466947021776">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.make_response(self.handle_exception(e))</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre>
<pre class="line after"><span class="ws">            </span>if self.should_ignore_error(error):</pre>
<pre class="line after"><span class="ws">                </span>error = None</pre>
<pre class="line after"><span class="ws">            </span>ctx.auto_pop(error)</pre></div>
</div>

<li><div class="frame" id="frame-140466947021840">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span># if we want to repropagate the exception, we can attempt to</pre>
<pre class="line before"><span class="ws">            </span># raise it with the whole traceback in case we can do that</pre>
<pre class="line before"><span class="ws">            </span># (the function was actually called from the except part)</pre>
<pre class="line before"><span class="ws">            </span># otherwise, we just raise the error again</pre>
<pre class="line before"><span class="ws">            </span>if exc_value is e:</pre>
<pre class="line current"><span class="ws">                </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws">            </span>else:</pre>
<pre class="line after"><span class="ws">                </span>raise e</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>self.log_exception((exc_type, exc_value, tb))</pre>
<pre class="line after"><span class="ws">        </span>if handler is None:</pre></div>
</div>

<li><div class="frame" id="frame-140466947021904">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>ctx.push()</pre>
<pre class="line before"><span class="ws">        </span>error = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.make_response(self.handle_exception(e))</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-140466947021968">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>response = self.make_response(rv)</pre>
<pre class="line after"><span class="ws">        </span>response = self.process_response(response)</pre>
<pre class="line after"><span class="ws">        </span>request_finished.send(self, response=response)</pre>
<pre class="line after"><span class="ws">        </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140466947022032">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>app_handlers = self.error_handler_spec[None].get(None, ())</pre>
<pre class="line before"><span class="ws">        </span>for typecheck, handler in chain(blueprint_handlers, app_handlers):</pre>
<pre class="line before"><span class="ws">            </span>if isinstance(e, typecheck):</pre>
<pre class="line before"><span class="ws">                </span>return handler(e)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line current"><span class="ws">        </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def handle_exception(self, e):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Default exception handling that kicks in when an exception</pre>
<pre class="line after"><span class="ws">        </span>occurs that is not caught.  In debug mode the exception will</pre>
<pre class="line after"><span class="ws">        </span>be re-raised immediately, otherwise it is logged and the handler</pre></div>
</div>

<li><div class="frame" id="frame-140466947022096">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>self.try_trigger_before_first_request_functions()</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>response = self.make_response(rv)</pre>
<pre class="line after"><span class="ws">        </span>response = self.process_response(response)</pre>
<pre class="line after"><span class="ws">        </span>request_finished.send(self, response=response)</pre></div>
</div>

<li><div class="frame" id="frame-140466947022160">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span># request came with the OPTIONS method, reply automatically</pre>
<pre class="line before"><span class="ws">        </span>if getattr(rule, 'provide_automatic_options', False) \</pre>
<pre class="line before"><span class="ws">           </span>and req.method == 'OPTIONS':</pre>
<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line current"><span class="ws">        </span>return self.view_functions[rule.endpoint](**req.view_args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws">        </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-140466947022224">
  <h4>File <cite class="filename">"/vagrant/app/main/views.py"</cite>,
      line <em class="line">30</em>,
      in <code class="function">api</code></h4>
  <div class="source"><pre class="line before"><span class="ws">    </span>if request.content_type in allowed_content:</pre>
<pre class="line before"><span class="ws">        </span>jsonData = request.get_json()</pre>
<pre class="line before"><span class="ws">        </span>current_app.logger.debug(&quot;请求json数据为： {}&quot;.format(json.dumps(jsonData)))</pre>
<pre class="line before"><span class="ws">        </span>jsonrpc = JsonRpc(jsonData)</pre>
<pre class="line before"><span class="ws">        </span>jsonrpc.jsonData = jsonData</pre>
<pre class="line current"><span class="ws">        </span>ret = jsonrpc.execute()</pre>
<pre class="line after"><span class="ws">        </span>return json.dumps(ret, ensure_ascii=False)</pre>
<pre class="line after"><span class="ws">    </span>else:</pre>
<pre class="line after"><span class="ws">        </span>current_app.logger.debug(&quot;用户请求的content-type为： {}, 不予处理&quot;.format(request.content_type))</pre>
<pre class="line after"><span class="ws">        </span>return &quot;200&quot;, 400</pre></div>
</div>

<li><div class="frame" id="frame-140466947022416">
  <h4>File <cite class="filename">"/vagrant/app/base/__init__.py"</cite>,
      line <em class="line">44</em>,
      in <code class="function">execute</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span>105: &quot;id不正确，应该是1&quot;</pre>
<pre class="line before"><span class="ws">        </span>}</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def execute(self):</pre>
<pre class="line before"><span class="ws">        </span># 验证id # 验证jsondata</pre>
<pre class="line current"><span class="ws">        </span>if self.runAllValidata():</pre>
<pre class="line after"><span class="ws">            </span>print &quot;验证通过：&quot; + &quot;等待调用方法！&quot;</pre>
<pre class="line after"><span class="ws">            </span>result = getattr(self.module, self.funcname)(**self.params)</pre>
<pre class="line after"><span class="ws">            </span># str1 = &quot;{}.{}&quot;.format(self.module, self.funcname)</pre>
<pre class="line after"><span class="ws">            </span># result = eval(str1)(**self.params)</pre>
<pre class="line after"><span class="ws">            </span># result =</pre></div>
</div>

<li><div class="frame" id="frame-140466947022288">
  <h4>File <cite class="filename">"/vagrant/app/base/__init__.py"</cite>,
      line <em class="line">144</em>,
      in <code class="function">runAllValidata</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>[description]手工维护validata list容易出错，改造成inspect</pre>
<pre class="line before"><span class="ws">        </span>#[self.validate_mandatory, self.validata_id, self.validata_HasModule, self.validata_hasFunction]:</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;</pre>
<pre class="line before"><span class="ws">        </span>validata_result = True</pre>
<pre class="line before"><span class="ws">        </span>for func in list(inspect.getmembers(self, predicate=inspect.ismethod)):</pre>
<pre class="line current"><span class="ws">            </span>if (func[0][:8] == 'validata') and (not func[1]()) :</pre>
<pre class="line after"><span class="ws">                </span>#print &quot;====&quot; + str(func[1]())</pre>
<pre class="line after"><span class="ws">                </span>validata_result = False</pre>
<pre class="line after"><span class="ws">        </span>return validata_result</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-140466947022544">
  <h4>File <cite class="filename">"/vagrant/app/base/__init__.py"</cite>,
      line <em class="line">132</em>,
      in <code class="function">validata_hasFunction</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span># 这个条件判断意义不大(not self.module)</pre>
<pre class="line before"><span class="ws">        </span>if hasattr(self.module, self.funcname):</pre>
<pre class="line before"><span class="ws">            </span>validata_result = True</pre>
<pre class="line before"><span class="ws">        </span>else:</pre>
<pre class="line before"><span class="ws">            </span>self.response_preform.printlogs(</pre>
<pre class="line current"><span class="ws">                </span>&quot;模块&quot; + self.module_name + &quot;没有此函数&quot; + self.funcname)</pre>
<pre class="line after"><span class="ws">            </span>validata_result = False</pre>
<pre class="line after"><span class="ws">        </span>return validata_result</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def runAllValidata(self):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;[summary]验证json的元素是否正确</pre></div>
</div>
</ul>
  <blockquote>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 144, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 132, in validata_hasFunction
    "模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 144, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 132, in validata_hasFunction
    "模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

-->

(python27env) [vagrant@OpsDev2 test]$ ^C
(python27env) [vagrant@OpsDev2 test]$ python testAPI.py 
200
"{\n    \"jsonrpc\": \"2.0\", \n    \"result\": \"测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}\", \n    \"id\": 1\n}"
500
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <title>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128) // Werkzeug Debugger</title>
    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"
        type="text/css">
    <!-- We need to make sure this has a favicon so that the debugger does
         not by accident trigger a request to /favicon.ico which might
         change the application state. -->
    <link rel="shortcut icon"
        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>
    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>
    <script type="text/javascript">
      var TRACEBACK = 139838316695248,
          CONSOLE_MODE = false,
          EVALEX = true,
          EVALEX_TRUSTED = false,
          SECRET = "VuKYX82P8DOI4tiVFrTO";
    </script>
  </head>
  <body>
    <div class="debugger">
<h1>UnicodeDecodeError</h1>
<div class="detail">
  <p class="errormsg">UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</p>
</div>
<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>
<div class="traceback">
  
  <ul><li><div class="frame" id="frame-139838316695120">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1836</em>,
      in <code class="function">__call__</code></h4>
  <div class="source"><pre class="line before"><span class="ws">                                </span>'Flask.blueprints instead'), stacklevel=2)</pre>
<pre class="line before"><span class="ws">        </span>return self.blueprints</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;Shortcut for :attr:`wsgi_app`.&quot;&quot;&quot;</pre>
<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def __repr__(self):</pre>
<pre class="line after"><span class="ws">        </span>return '&lt;%s %r&gt;' % (</pre>
<pre class="line after"><span class="ws">            </span>self.__class__.__name__,</pre>
<pre class="line after"><span class="ws">            </span>self.name,</pre></div>
</div>

<li><div class="frame" id="frame-139838316695312">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1820</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line before"><span class="ws">                </span>error = e</pre>
<pre class="line current"><span class="ws">                </span>response = self.make_response(self.handle_exception(e))</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre>
<pre class="line after"><span class="ws">            </span>if self.should_ignore_error(error):</pre>
<pre class="line after"><span class="ws">                </span>error = None</pre>
<pre class="line after"><span class="ws">            </span>ctx.auto_pop(error)</pre></div>
</div>

<li><div class="frame" id="frame-139838316695376">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1403</em>,
      in <code class="function">handle_exception</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span># if we want to repropagate the exception, we can attempt to</pre>
<pre class="line before"><span class="ws">            </span># raise it with the whole traceback in case we can do that</pre>
<pre class="line before"><span class="ws">            </span># (the function was actually called from the except part)</pre>
<pre class="line before"><span class="ws">            </span># otherwise, we just raise the error again</pre>
<pre class="line before"><span class="ws">            </span>if exc_value is e:</pre>
<pre class="line current"><span class="ws">                </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws">            </span>else:</pre>
<pre class="line after"><span class="ws">                </span>raise e</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">        </span>self.log_exception((exc_type, exc_value, tb))</pre>
<pre class="line after"><span class="ws">        </span>if handler is None:</pre></div>
</div>

<li><div class="frame" id="frame-139838316695440">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1817</em>,
      in <code class="function">wsgi_app</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>
<pre class="line before"><span class="ws">        </span>ctx.push()</pre>
<pre class="line before"><span class="ws">        </span>error = None</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>try:</pre>
<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()</pre>
<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">                </span>error = e</pre>
<pre class="line after"><span class="ws">                </span>response = self.make_response(self.handle_exception(e))</pre>
<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>
<pre class="line after"><span class="ws">        </span>finally:</pre></div>
</div>

<li><div class="frame" id="frame-139838316695504">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1477</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>response = self.make_response(rv)</pre>
<pre class="line after"><span class="ws">        </span>response = self.process_response(response)</pre>
<pre class="line after"><span class="ws">        </span>request_finished.send(self, response=response)</pre>
<pre class="line after"><span class="ws">        </span>return response</pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-139838316879952">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1381</em>,
      in <code class="function">handle_user_exception</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>app_handlers = self.error_handler_spec[None].get(None, ())</pre>
<pre class="line before"><span class="ws">        </span>for typecheck, handler in chain(blueprint_handlers, app_handlers):</pre>
<pre class="line before"><span class="ws">            </span>if isinstance(e, typecheck):</pre>
<pre class="line before"><span class="ws">                </span>return handler(e)</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line current"><span class="ws">        </span>reraise(exc_type, exc_value, tb)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def handle_exception(self, e):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Default exception handling that kicks in when an exception</pre>
<pre class="line after"><span class="ws">        </span>occurs that is not caught.  In debug mode the exception will</pre>
<pre class="line after"><span class="ws">        </span>be re-raised immediately, otherwise it is logged and the handler</pre></div>
</div>

<li><div class="frame" id="frame-139838316880016">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1475</em>,
      in <code class="function">full_dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>self.try_trigger_before_first_request_functions()</pre>
<pre class="line before"><span class="ws">        </span>try:</pre>
<pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>
<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>
<pre class="line before"><span class="ws">            </span>if rv is None:</pre>
<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()</pre>
<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>
<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>
<pre class="line after"><span class="ws">        </span>response = self.make_response(rv)</pre>
<pre class="line after"><span class="ws">        </span>response = self.process_response(response)</pre>
<pre class="line after"><span class="ws">        </span>request_finished.send(self, response=response)</pre></div>
</div>

<li><div class="frame" id="frame-139838316880080">
  <h4>File <cite class="filename">"/data/python27env/lib/python2.7/site-packages/flask/app.py"</cite>,
      line <em class="line">1461</em>,
      in <code class="function">dispatch_request</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span># request came with the OPTIONS method, reply automatically</pre>
<pre class="line before"><span class="ws">        </span>if getattr(rule, 'provide_automatic_options', False) \</pre>
<pre class="line before"><span class="ws">           </span>and req.method == 'OPTIONS':</pre>
<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>
<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>
<pre class="line current"><span class="ws">        </span>return self.view_functions[rule.endpoint](**req.view_args)</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Dispatches the request and on top of that performs request</pre>
<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>
<pre class="line after"><span class="ws">        </span>error handling.</pre></div>
</div>

<li><div class="frame" id="frame-139838316880144">
  <h4>File <cite class="filename">"/vagrant/app/main/views.py"</cite>,
      line <em class="line">30</em>,
      in <code class="function">api</code></h4>
  <div class="source"><pre class="line before"><span class="ws">    </span>if request.content_type in allowed_content:</pre>
<pre class="line before"><span class="ws">        </span>jsonData = request.get_json()</pre>
<pre class="line before"><span class="ws">        </span>current_app.logger.debug(&quot;请求json数据为： {}&quot;.format(json.dumps(jsonData)))</pre>
<pre class="line before"><span class="ws">        </span>jsonrpc = JsonRpc(jsonData)</pre>
<pre class="line before"><span class="ws">        </span>jsonrpc.jsonData = jsonData</pre>
<pre class="line current"><span class="ws">        </span>ret = jsonrpc.execute()</pre>
<pre class="line after"><span class="ws">        </span>return json.dumps(ret, ensure_ascii=False)</pre>
<pre class="line after"><span class="ws">    </span>else:</pre>
<pre class="line after"><span class="ws">        </span>current_app.logger.debug(&quot;用户请求的content-type为： {}, 不予处理&quot;.format(request.content_type))</pre>
<pre class="line after"><span class="ws">        </span>return &quot;200&quot;, 400</pre></div>
</div>

<li><div class="frame" id="frame-139838316880336">
  <h4>File <cite class="filename">"/vagrant/app/base/__init__.py"</cite>,
      line <em class="line">44</em>,
      in <code class="function">execute</code></h4>
  <div class="source"><pre class="line before"><span class="ws">            </span>105: &quot;id不正确，应该是1&quot;</pre>
<pre class="line before"><span class="ws">        </span>}</pre>
<pre class="line before"><span class="ws"></span> </pre>
<pre class="line before"><span class="ws">    </span>def execute(self):</pre>
<pre class="line before"><span class="ws">        </span># 验证id # 验证jsondata</pre>
<pre class="line current"><span class="ws">        </span>if self.runAllValidata():</pre>
<pre class="line after"><span class="ws">            </span>print &quot;验证通过：&quot; + &quot;等待调用方法！&quot;</pre>
<pre class="line after"><span class="ws">            </span>result = getattr(self.module, self.funcname)(**self.params)</pre>
<pre class="line after"><span class="ws">            </span># str1 = &quot;{}.{}&quot;.format(self.module, self.funcname)</pre>
<pre class="line after"><span class="ws">            </span># result = eval(str1)(**self.params)</pre>
<pre class="line after"><span class="ws">            </span># result =</pre></div>
</div>

<li><div class="frame" id="frame-139838316880208">
  <h4>File <cite class="filename">"/vagrant/app/base/__init__.py"</cite>,
      line <em class="line">143</em>,
      in <code class="function">runAllValidata</code></h4>
  <div class="source"><pre class="line before"><span class="ws">        </span>[description]手工维护validata list容易出错，改造成inspect</pre>
<pre class="line before"><span class="ws">        </span>#[self.validate_mandatory, self.validata_id, self.validata_HasModule, self.validata_hasFunction]:</pre>
<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;</pre>
<pre class="line before"><span class="ws">        </span>validata_result = True</pre>
<pre class="line before"><span class="ws">        </span>for func in list(inspect.getmembers(self, predicate=inspect.ismethod)):</pre>
<pre class="line current"><span class="ws">            </span>if (func[0][:8] == 'validata') and (not func[1]()) :</pre>
<pre class="line after"><span class="ws">                </span>#print &quot;====&quot; + str(func[1]())</pre>
<pre class="line after"><span class="ws">                </span>validata_result = False</pre>
<pre class="line after"><span class="ws">        </span>return validata_result</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws"></span> </pre></div>
</div>

<li><div class="frame" id="frame-139838316880464">
  <h4>File <cite class="filename">"/vagrant/app/base/__init__.py"</cite>,
      line <em class="line">131</em>,
      in <code class="function">validata_hasFunction</code></h4>
  <div class="source"><pre class="line before"><span class="ws">    </span>def validata_hasFunction(self):</pre>
<pre class="line before"><span class="ws">        </span># 这个条件判断意义不大(not self.module)</pre>
<pre class="line before"><span class="ws">        </span>if hasattr(self.module, self.funcname):</pre>
<pre class="line before"><span class="ws">            </span>validata_result = True</pre>
<pre class="line before"><span class="ws">        </span>else:</pre>
<pre class="line current"><span class="ws">            </span>self.response_preform.printlogs(&quot;模块&quot; + self.module_name + &quot;没有此函数&quot; + self.funcname)</pre>
<pre class="line after"><span class="ws">            </span>validata_result = False</pre>
<pre class="line after"><span class="ws">        </span>return validata_result</pre>
<pre class="line after"><span class="ws"></span> </pre>
<pre class="line after"><span class="ws">    </span>def runAllValidata(self):</pre>
<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;[summary]验证json的元素是否正确</pre></div>
</div>
</ul>
  <blockquote>UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</blockquote>
</div>

<div class="plain">
  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">
    <p>
      <input type="hidden" name="language" value="pytb">
      This is the Copy/Paste friendly version of the traceback.  <span
      class="pastemessage">You can also paste this traceback into
      a <a href="https://gist.github.com/">gist</a>:
      <input type="submit" value="create paste"></span>
    </p>
    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 143, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 131, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)</textarea>
  </form>
</div>
<div class="explanation">
  The debugger caught an exception in your WSGI application.  You can now
  look at the traceback which led to the error.  <span class="nojavascript">
  If you enable JavaScript you can also use additional features such as code
  execution (if the evalex feature is enabled), automatic pasting of the
  exceptions and much more.</span>
</div>
      <div class="footer">
        Brought to you by <strong class="arthur">DON'T PANIC</strong>, your
        friendly Werkzeug powered traceback interpreter.
      </div>
    </div>

    <div class="pin-prompt">
      <div class="inner">
        <h3>Console Locked</h3>
        <p>
          The console is locked and needs to be unlocked by entering the PIN.
          You can find the PIN printed out on the standard output of your
          shell that runs the server.
        <form>
          <p>PIN:
            <input type=text name=pin size=14>
            <input type=submit name=btn value="Confirm Pin">
        </form>
      </div>
    </div>
  </body>
</html>

<!--

Traceback (most recent call last):
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/python27env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/vagrant/app/main/views.py", line 30, in api
    ret = jsonrpc.execute()
  File "/vagrant/app/base/__init__.py", line 44, in execute
    if self.runAllValidata():
  File "/vagrant/app/base/__init__.py", line 143, in runAllValidata
    if (func[0][:8] == 'validata') and (not func[1]()) :
  File "/vagrant/app/base/__init__.py", line 131, in validata_hasFunction
    self.response_preform.printlogs("模块" + self.module_name + "没有此函数" + self.funcname)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

-->

(python27env) [vagrant@OpsDev2 test]$ python testAPI.py 
Traceback (most recent call last):
  File "testAPI.py", line 41, in <module>
    test_api()
  File "testAPI.py", line 32, in test_api
    r = requests.post(url, headers=header, data=json.dumps(format_Request))
  File "/data/python27env/lib/python2.7/site-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/data/python27env/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/python27env/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/python27env/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/data/python27env/lib/python2.7/site-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f60a6f6b510>: Failed to establish a new connection: [Errno 111] Connection refused',))
(python27env) [vagrant@OpsDev2 test]$ python testAPI.py 
200
"{\n    \"jsonrpc\": \"2.0\", \n    \"result\": \"测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}\", \n    \"id\": 1\n}"
200
"{\n    \"error_code\": 100, \n    \"jsonrpc\": \"2.0\", \n    \"id\": \"2\", \n    \"errmsg\": \"jsonrpc调用失败，详见系统后台日志！\"\n}"
(python27env) [vagrant@OpsDev2 test]$ python testAPI.py 
200
"{\n    \"jsonrpc\": \"2.0\", \n    \"result\": \"测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}\", \n    \"id\": 1\n}"
200
"{\n    \"error_code\": 100, \n    \"jsonrpc\": \"2.0\", \n    \"id\": \"2\", \n    \"errmsg\": \"jsonrpc调用失败，详见系统后台日志！\"\n}"
(python27env) [vagrant@OpsDev2 test]$ python testAPI.py 
200
"{\n    \"jsonrpc\": \"2.0\", \n    \"result\": \"测试getIdc()方法:返回传过来的参数{u'idcId': u'2'}\", \n    \"id\": 1\n}"
200
"{\n    \"error_code\": 100, \n    \"jsonrpc\": \"2.0\", \n    \"id\": \"2\", \n    \"errmsg\": \"jsonrpc调用失败，详见系统后台日志！\"\n}"
(python27env) [vagrant@OpsDev2 test]$ 
```
